### PR TITLE
Icon class is `OctIcons` not `Octicons`

### PR DESCRIPTION
**Pull request by alexcmgit**

### CODE REVIEW

**Comment by Coronon** [comment]
Hi, thanks for your PR. I was super busy and only noticed now - sorry :)

**Comment by Coronon** [comment]
Published 👍🏻

**Comment by alexcmgit** [comment]
Nah, don't worry. Thanks for taking time to publish! ;)

**Comment by Coronon** [comment]
> Nah, don't worry. Thanks for taking time to publish! ;)

Thats the awesome thing about automation: I just have to press a button for the Action to run ;)

**Pull request merged**
